### ISSUE TITLE
an issues with ComponentGroup.cs

### ISSUE THREAD

**Issue by views63** [Spy-Shifty/BrokenBricksECS#1]
In the file: ComponentGroup.cs line:65, Did you make a mistake here?

<img width="699" alt="1" src="https://user-images.githubusercontent.com/175116/32868851-017baca0-caaf-11e7-9098-6d997ef94d01.png">

**Comment by Spy-Shifty** [comment]
Thank you for your report, I fixed it instantly 635948669098e498944587ff948baa5f537bbe32
