### ISSUE TITLE
Debug System Behaviour shows incorrect number of Update Systems.

### ISSUE THREAD

**Issue by Filtiarn00** [Spy-Shifty/BrokenBricksECS#24]
Here is a picture.
https://forum.unity.com/attachments/capture-png.262905/

**Comment by Filtiarn00** [comment]
Got It to be correct.

Under Debug Systems I changed in totalOnUpdateSystemsCount 
I changed 
`total += debugSystems != null ? debugSystems.totalOnUpdateSystemsCount : _updateSystemInfos.Count;`
to
`total = debugSystems != null ? debugSystems.totalOnUpdateSystemsCount : _updateSystemInfos.Count;`
this works to
`total += debugSystems != null ? 0 : 1;`

This should be done for Start and Fixed Update as well.

**Comment by Spy-Shifty** [comment]
Thank you I'll integrate this in the next update :)

**Comment by Spy-Shifty** [comment]
I fixed this problem 0ed8c5bd2d9bb7738dd34239179b9783ab51e85c

Your solution wasn't 100% correct.

See commit. 
But thank you anyway :)

Ps: You can group Systems together. So you can disable a group of systems or to monitor the total performance of the systems. 
Just use the  DebugSystemGroup Attribute
