### ISSUE TITLE
Entity added event called multiple times for groups on add component

### ISSUE THREAD

**Issue by acoppes** [Spy-Shifty/BrokenBricksECS#8]
After adding all components of interest for a group, entity added is called as it should, but after another component is added, the group validates again and call entity added event.

Here is the code to replicate the bug, the test fails, the listener is called a second time after Component3 is added:

```
using NUnit.Framework;
using ECS;

public class TestGroupCallbacks {

	class Component1 : IComponent
	{
		
	}

	class Component2 : IComponent
	{
		
	}

	class Component3 : IComponent
	{

	}

	class ListenerMock : IEntityAddedEventListener
	{
		public int timesCalled;

		#region IEntityAddedEventListener implementation
		public void OnEntityAdded (object sender, Entity entity)
		{
			timesCalled++;
		}
		#endregion
		
	}

	[Test]
	public void EntityAddedToGroupShouldNotBeCalledIfDifferentComponent() {
		// Use the Assert class to test conditions.

		var entityManager = new EntityManager ();
		var group = entityManager.GetComponentGroup (typeof(Component1), typeof(Component2));

		var listenerMock = new ListenerMock ();
		group.SubscribeOnEntityAdded (listenerMock);

		var e = entityManager.CreateEntity ();
		entityManager.AddComponent (e, new Component1 ());
		entityManager.AddComponent (e, new Component2 ());
		Assert.That (listenerMock.timesCalled, Is.EqualTo (1));
		entityManager.AddComponent (e, new Component3 ());
		Assert.That (listenerMock.timesCalled, Is.EqualTo (1));
	}

}
```

**Comment by Spy-Shifty** [comment]
Solved fa41bb30009e3d41b55574d5ce484bdf1b2802a0

Thank you for submitting! If you have more unit tests I would be happy if you could submit them to me. Anyway, I'll have to write some!

**Comment by acoppes** [comment]
I downloaded latest code and the test still fails for me. 

You can add the test to the project if you want. I added it as a Unity test because it was easier for me but it should be easily changed to be a nunit test or something like that.

**Comment by Spy-Shifty** [comment]
I've also downloaded it (different computer) and the test runs successfully. Try it again. Maybe you missed something. If it doesn't work, let me know!

**Comment by acoppes** [comment]
My mistake, I had the ECS code in another folder for the unity project test I was working on.

BTW, you changed the API of the ComponentSystem, I cannot override the OnEntityAdded anymore :(, I have to see how to do what I was doing with the new API.
